include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - directives_ordering
    - document_ignores
    - noop_primitive_operations
    - only_throw_errors
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_mixin
    - require_trailing_commas
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_statements
    - use_string_buffers
